---
title: "Final_Project_Work_HW2_JaJuArEm"
author: "Jacob Kresnicka"
date: "2022-09-21"
output: html_document
---

# library statements 

```{r}
library(ISLR)
library(dplyr)
library(readr)
library(broom)
library(ggplot2)
library(tidymodels) 
library(stringr)
library(splitstackshape)
tidymodels_prefer()
```

# read in data

```{r}
library(readr)
imdb_top_1000 <- read_csv("~/Desktop/Statistical Machine Learning/R Files/Final Project/imdb_top_1000.csv")
View(imdb_top_1000)
```

# data cleaning

```{r}
imdb_clean <- imdb_top_1000 %>%
  select(-Poster_Link, -Certificate) %>%
  cSplit("Genre", sep = ",", direction = "wide")

runtime_clean <- imdb_top_1000$Runtime %>%
  str_replace(" min", "") %>%
  as.numeric()

imdb_clean$Runtime <- runtime_clean
```

# creation of cv folds

```{r}
data_cv10 <- vfold_cv(imdb_clean, v = 10)
```

# model spec

```{r}
lm_spec <-
    linear_reg() %>% 
    set_engine(engine = 'lm') %>% 
    set_mode('regression')
```

# recipes & workflows

```{r}
full_rec <- recipe(Gross ~ ., data = imdb_clean) %>%
    #step_rm(Series_Title, Released_Year, Overview) %>% variables causing issues, maybe this will work
    step_nzv(all_predictors()) %>% 
    step_normalize(all_numeric_predictors()) %>% 
    step_dummy(all_nominal_predictors()) 
    
full_lm_wf <- workflow() %>%
    add_recipe(full_rec) %>%
    add_model(lm_spec)
    
full_model <- fit(full_lm_wf, data = imdb_clean) 

full_model %>% tidy()
```


# fit & tune models

```{r}

```
